# Generated by Django 2.0.7 on 2018-09-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interpreted', models.DateField(auto_now=True)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Whisper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whispered', models.DateField(auto_now=True)),
                ('og_text', models.CharField(max_length=200)),
                ('interpretations', models.ManyToManyField(to='whispers.Interpretation')),
            ],
        ),
    ]
