# Generated by Django 2.0.7 on 2018-09-26 02:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('whispers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whisper',
            name='display_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='whisper',
            name='id',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
