# Generated by Django 2.0.7 on 2018-09-27 03:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interpretation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interpreted', models.DateField(auto_now=True)),
                ('text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Whisper',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('whispered', models.DateField(auto_now=True)),
                ('og_text', models.CharField(max_length=200)),
                ('display_text', models.CharField(blank=True, max_length=200)),
                ('intentification_num', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('interpretations', models.ManyToManyField(blank=True, to='whispers.Interpretation')),
            ],
        ),
    ]
