# Generated by Django 2.0.7 on 2018-09-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whispers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whisper',
            name='created_by_user_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
